# Generated by Django 5.1.7 on 2025-08-16 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?[0-9\\s\\-]+$')])),
                ('sujet', models.CharField(choices=[('commande', 'Problème ou question sur une commande'), ('livraison', 'Problème ou retard de livraison'), ('produit', 'Question sur un produit (goût, disponibilité, allergènes, etc.)'), ('paiement', 'Problème de paiement'), ('partenariat', 'Demande de partenariat ou collaboration'), ('suggestion', 'Suggestion ou amélioration'), ('autre', 'Autre demande')], max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
