# Generated by Django 5.2 on 2025-10-18 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produit',
            name='CGAPP_produ_nom_df9a5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='CGAPP_produ_categor_02867b_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='CGAPP_produ_prix_ee2210_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='CGAPP_produ_est_pop_a8604e_idx',
        ),
        migrations.AddField(
            model_name='produit',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin créateur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='est_populaire',
            field=models.BooleanField(default=False, verbose_name='Produit populaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='gerant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='CGAPP.gerant', verbose_name='Gérant responsable'),
        ),
    ]
