# Generated by Django 5.1.7 on 2025-08-01 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='date_commande',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CGAPP.adresselivraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CGAPP.coupon'),
        ),
    ]
