# Generated by Django 5.2.1 on 2025-08-03 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0002_coupon_rename_date_commande_commande_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='CGAPP.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGAPP.produit')),
            ],
        ),
    ]
