# Generated by Django 5.2.1 on 2025-08-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0003_lignecommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('connexion', 'Connexion'), ('commande_statut', 'Changement statut commande'), ('produit_ajout', 'Ajout produit'), ('produit_modif', 'Modification produit'), ('produit_suppr', 'Suppression produit'), ('utilisateur_creation', 'Création utilisateur'), ('utilisateur_suspension', 'Suspension utilisateur'), ('configuration', 'Modification configuration')], max_length=25)),
                ('description', models.TextField()),
                ('objet_concerne', models.CharField(blank=True, max_length=100, null=True)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details_supplementaires', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historique des actions',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('commande_confirmee', 'Commande confirmée'), ('commande_preparation', 'Commande en préparation'), ('commande_livraison', 'Commande en livraison'), ('commande_livree', 'Commande livrée'), ('commande_annulee', 'Commande annulée'), ('produit_stock_bas', 'Stock produit bas'), ('nouveau_message', 'Nouveau message contact')], max_length=25)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CGAPP.commande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
