# Generated by Django 5.2.5 on 2025-09-02 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0003_paiement_reference_alter_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_traitement', 'En traitement'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ - Très mauvais'), (2, '★★☆☆☆ - Mauvais'), (3, '★★★☆☆ - Moyen'), (4, '★★★★☆ - Bon'), (5, '★★★★★ - Excellent')], verbose_name='Note')),
                ('titre', models.CharField(max_length=100, verbose_name="Titre de l'avis")),
                ('commentaire', models.TextField(verbose_name='Votre commentaire')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques supplémentaires')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Avis approuvé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='CGAPP.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='CGAPP.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_produits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis produit',
                'verbose_name_plural': 'Avis produits',
                'ordering': ['-date_creation'],
                'unique_together': {('utilisateur', 'produit', 'commande')},
            },
        ),
        migrations.CreateModel(
            name='MediaAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avis/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='CGAPP.avisproduit')),
            ],
            options={
                'verbose_name': "Média d'avis",
                'verbose_name_plural': "Médias d'avis",
            },
        ),
        migrations.CreateModel(
            name='PreferenceAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('allergie', 'Allergie'), ('intolerance', 'Intolérance'), ('preference', 'Préférence alimentaire'), ('regime', 'Régime spécial'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(verbose_name='Description de la préférence/allergie')),
                ('severite', models.CharField(choices=[('leger', 'Léger'), ('modere', 'Modéré'), ('severe', 'Sévère'), ('critique', 'Critique')], default='modere', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_alimentaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence alimentaire',
                'verbose_name_plural': 'Préférences alimentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la réponse')),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='CGAPP.avisproduit')),
            ],
            options={
                'verbose_name': "Réponse à l'avis",
                'verbose_name_plural': 'Réponses aux avis',
                'ordering': ['date_creation'],
            },
        ),
    ]
