# Generated by Django 5.2.5 on 2025-09-03 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0004_alter_commande_statut_avisproduit_mediaavis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotationCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_globale', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ - Très mauvais'), (2, '★★☆☆☆ - Mauvais'), (3, '★★★☆☆ - Moyen'), (4, '★★★★☆ - Bon'), (5, '★★★★★ - Excellent')], verbose_name='Note globale')),
                ('note_livraison', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ - Très mauvais'), (2, '★★☆☆☆ - Mauvais'), (3, '★★★☆☆ - Moyen'), (4, '★★★★☆ - Bon'), (5, '★★★★★ - Excellent')], verbose_name='Note livraison')),
                ('note_emballage', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ - Très mauvais'), (2, '★★☆☆☆ - Mauvais'), (3, '★★★☆☆ - Moyen'), (4, '★★★★☆ - Bon'), (5, '★★★★★ - Excellent')], verbose_name='Note emballage')),
                ('commentaire', models.TextField(verbose_name='Commentaire sur la commande')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques supplémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='CGAPP.commande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations_commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notation de commande',
                'verbose_name_plural': 'Notations de commandes',
                'unique_together': {('utilisateur', 'commande')},
            },
        ),
        migrations.CreateModel(
            name='MediaNotationCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notations-commandes/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='CGAPP.notationcommande')),
            ],
            options={
                'verbose_name': 'Média de notation',
                'verbose_name_plural': 'Médias de notations',
            },
        ),
        migrations.CreateModel(
            name='ProblemeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('produit_manquant', 'Produit manquant'), ('produit_abime', 'Produit abîmé'), ('produit_erreur', 'Mauvais produit reçu'), ('emballage', "Problème d'emballage"), ('livraison', 'Problème de livraison'), ('qualite', 'Problème de qualité'), ('autre', 'Autre problème')], max_length=20, verbose_name='Type de problème')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('resolu', models.BooleanField(default=False, verbose_name='Problème résolu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='CGAPP.commande')),
                ('photos', models.ManyToManyField(blank=True, to='CGAPP.medianotationcommande', verbose_name='Photos')),
                ('produit_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CGAPP.produit', verbose_name='Produit concerné')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes_commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problème de commande',
                'verbose_name_plural': 'Problèmes de commandes',
            },
        ),
    ]
