# Generated by Django 5.2 on 2025-09-12 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0005_notationcommande_medianotationcommande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['cle'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='reduction',
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_debut',
            field=models.DateTimeField(default=1, verbose_name='Date de début'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='type_reduction',
            field=models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], default='pourcentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_actuel',
            field=models.PositiveIntegerField(default=0, verbose_name='Utilisation actuelle'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_max',
            field=models.PositiveIntegerField(default=1, verbose_name='Utilisation maximum'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valeur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valeur de la réduction'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code du coupon'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('serveur', 'Serveur'), ('gerant', 'Gérant'), ('livreur', 'Livreur')], max_length=10),
        ),
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journaux de connexions',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SauvegardeSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='sauvegardes/')),
                ('taille', models.BigIntegerField(help_text='Taille en octets')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sauvegarde système',
                'verbose_name_plural': 'Sauvegardes système',
                'ordering': ['-date_creation'],
            },
        ),
    ]
