# Generated by Django 5.2.1 on 2025-09-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0007_commande_date_livraison_commande_date_modification_and_more'),
        ('CGAPP', '0007_fix_parametresysteme'),
    ]

    operations = [
    ]
