# Generated by Django 5.2 on 2025-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0007_parametresysteme_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
