# Generated by Django 5.2 on 2025-10-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CGAPP', '0008_merge_20250913_1848'),
        ('CGAPP', '0008_paiement_transaction_id'),
    ]

    operations = [
    ]
